# Generated by Django 6.0 on 2025-12-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='describtion',
            new_name='description',
        ),
    ]
