# Generated by Django 6.0 on 2025-12-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='age',
            field=models.CharField(max_length=2),
        ),
    ]
